### ISSUE TITLE
Unable to merge: 1 disposition change and 1 acknowledgement to send loop

### ISSUE THREAD

**Issue by gkaempfer** [Reviewable/Reviewable#556]
Finish a review and publish LGTM but still get 0 drafts in red with the message "1 disposition change and 1 acknowledgement to send" and unable to merge.
This creates an endless series of publish/ack between reviewer and assignee :(

**Comment by pkaminski** [comment]
Sorry about that!  Could you please point me to the PR / review?  Did you use "Publish" to send the LGTM, or the single-message-send?

**Comment by gkaempfer** [comment]
It happened in all the PR's we tried to merge today. Eventually we forced
merges using local Git repo merges and pushed to master :(
We used Publish. I am not sure what you mean by "single-message-send".

**Comment by pkaminski** [comment]
That sounds bad indeed, but I still need a pointer to a sample PR so I can dig into the details.  It should be impossible for the drafts indicator to remain red after hitting Publish unless the publication fails.  I assume you didn't get any error messages?

**Comment by gkaempfer** [comment]
Plenty of examples:
https://reviewable.io/reviews/starkware-industries/starkware/12
https://reviewable.io/reviews/starkware-industries/starkware/14
https://reviewable.io/reviews/starkware-industries/starkware/16

(all merged forcefully)

The publication succeeded and dependency just moved to the PR creator. He
acknowledged and published and it moved back to me (the reviewer) etc etc.
Occasionally, I also got a permission denied error on the Publish.
Sometimes that went away when I deleted a comment or so.

**Comment by pkaminski** [comment]
Thanks.  I took a look at your and the other participant's state for those three reviews and there's nothing left that would cause the drafts indicator to go red.  Could you please spot check one of them to confirm that the drafts indicator is zeroed out and grey?

I fixed an issue with publishing replies to the top-level discussion earlier today.  I wonder if this is what prevented you from publishing altogether and accounts for the observed symptoms?  Have you observed the issue on a page loaded after 10:30pm Israel time today?

Apologies for the trouble!

**Comment by cblp** [comment]
I see this in any review. Also, the "Acknowledge" button under commit list doesn't click.

**Comment by gkaempfer** [comment]
Unfortunately the issue still persists as of the time of this comment :
![screenshot from 2018-05-28 15-04-19](https://user-images.githubusercontent.com/39151790/40613779-9ca5d96e-6288-11e8-9c31-b5379f9875e7.png)

**Comment by almalino** [comment]
Same with our reviewable client. All reviews stuck with red 0 next to draft

**Comment by pkaminski** [comment]
This is clearly a major issue so it's very frustrating that I can't reproduce it no matter what I try.  Can anyone provide more details that could lead to a repro, please?  (Always provide PR numbers even if it occurs for "all reviews".)

I need to go out for the next few hours but will be back in the afternoon local time.  If somebody can catch me in chat at that point we can do some pair-debugging and likely get to the bottom of this pretty quickly.

**Comment by pkaminski** [comment]
Actually, I now suspect this may be a weird browser compatibility issue.  Could you please report your browser version, and try with another browser if you have a minute?  Thanks!

**Comment by cblp** [comment]
Example review where I experience problems https://reviewable.io/reviews/ff-notes/ff/52

**Comment by almalino** [comment]
Google Chrome under Linux Version 66.0.3359.181 (Official Build) (64-bit)

**Comment by george-harness** [comment]
I have the same issue. What I noticed is for new PR I do not see the (0) Draws, but as soon as I get in, it gots created. My `Publish` button is enabled, but pressing it does nothing.

**Comment by george-harness** [comment]
I have the same version of chrome - 66.0.3359.181 (running on mac), but I can see the issue in safari too.

**Comment by pkaminski** [comment]
The browser compatibility hypothesis seems unlikely given the data so far.  :(  From the symptoms, it looks like Reviewable is counting empty acknowledgement and disposition change collections as having one member each for some reason, but publishing does nothing since they're actually empty.  The counting code is pretty trivial as you'd expect so I have no idea how it's failing.

I'll mostly be around at my machine until later tonight, so if anybody having this problem and 15-20 minutes to debug could drop by chat it would be really appreciated!

**Comment by jwnimmer-tri** [comment]
Also seeing this on all Drake PRs, such as RobotLocomotion/drake#8868 ([reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/8868)).

![image](https://user-images.githubusercontent.com/17596505/40635389-c9321d6e-62c7-11e8-92d0-1bd1ee269d7e.png)

The hovertext on the Publish button is "No drafts, 1 disposition change and 1 acknowledgement to send".

Pushing "Publish" greys for a moment but then comes back exactly how it was, still with the red zero.

For me this is happening on both FF 60.0.1 and Chome 66.0.3359.181 on Ubuntu 16.04.  The Chrome test was in a private window with fresh github login, so hopefully not any saved client state confusing things either.

**Comment by pkaminski** [comment]
At this point I'm pretty sure this is some kind of local state corruption (since the persisted state is clean), but the only way I'll figure it out is if I can poke around in a browser were this is happening.  Still no luck whatsoever with a repro; the issue is consistent across users (you're either affected or not) so it must have something to do with a setting or the environment, but I can't figure out what.

**Comment by pkaminski** [comment]
With @jwnimmer-tri's help I tracked the issue down to methods on a prototype being enumerable in some browsers but not others.  Once I knew what was going on, implementing a workaround was easy -- apologies for the trouble, things should be all right now!

**Comment by george-harness** [comment]
I still see the issue in some context - it is definitely better now, but not problem free

**Comment by pkaminski** [comment]
That's most unexpected.  Could you please drop in to chat to debug one such broken instance?  Thanks.

**Comment by george-harness** [comment]
Not sure if related `Acknowledge` button is not working too

**Comment by pkaminski** [comment]
In the same reviews where the drafts counter is broken, or is it a separate issue?

**Comment by george-harness** [comment]
Yes, in the same review

**Comment by pkaminski** [comment]
I reproduced and fixed one way in which Acknowledge was broken, please let me know if you still have trouble with it.  I'm stuck on the drafts counter unless you can jump in to a short chat to help me.

**Comment by gkaempfer** [comment]
Things seem to be working. Had one PR where GitHub rejected the merge from
Reviewable claiming a review was pending but from another computer the
merge worked just fine (maybe some local state got stuck there??)

**Comment by almalino** [comment]
Problem reduced from all PRs to single PR only having stuck with 0 draft. We will merge it directly via github and hopefully all new PRs will not have that problems. Thank you for fixing it :)

**Comment by george-harness** [comment]
I thought I might be having this last one thing myself, but I just experienced the think for a new PR

IT seems like the (0) draft pops after I publish reviews

**Comment by george-harness** [comment]
I am not sure what you mean with that?

**Comment by pkaminski** [comment]
Click Support > Chatroom to visit the chatroom, where I'll be able to to semi-interactively investigate your review's state by asking you to type stuff into the JS console for me.  This will let me quickly figure out exactly why the counts are off, and hopefully test a fix or workaround.

**Comment by george-harness** [comment]
unfortunately, this is asking for credentials that I do not have a permit to provide

**Comment by pkaminski** [comment]
Oh?  Sorry, I didn't realize `user:email` and `read:org` scopes would be controversial...  We can try via email or Google Hangouts, then, or whatever's convenient for you.  Let me know.

**Comment by pkaminski** [comment]
For the record and future readers, we didn't find another bug.  Rather, there's some confusion because acknowledgements used to work immediately but are now buffered and must be explicitly published.  This means that it's normal for the drafts count to switch from a grey zero to a red zero when you first hit acknowledge.
